name: Tests
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipenv install --dev --system
        pip install pytest
    - name: Run migrations
      run: |
        cd back
        mv back/.env.example back/.env
        sed -i "s/db:5432/127.0.0.1:5432/" back/.env
        python manage.py migrate
    - name: Check formatting flake8/black/isort
      run: |
        cd back
        flake8 .
        isort . -c
        black --check .
    - name: Test with pytest
      run: |
        cd back
        pytest --cov=./back/ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
    - name: Test fixtures
      run: |
        cd back
        python manage.py shell < fixtures/init_testing.py
        python manage.py loaddata all.json
        python manage.py loaddata welcome_message.json
        # - name: Login to DockerHub
        #   uses: docker/login-action@v1 
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_TOKEN }}
        # - name: Build and push
        #   id: docker_build
        #   uses: docker/build-push-action@v2
        #   with:
        #     context: https://github.com/chiefonboarding/ChiefOnboarding.git#deploy
        #     file: ./back/Dockerfile
        #     push: true
        #     tags: |
        #       chiefonboarding/chiefonboarding:latest
        #       chiefonboarding/chiefonboarding:1.2.13
# credits: https://hacksoft.io/github-actions-in-action-setting-up-django-and-postgres/
